### ISSUE TITLE
[Bug]: Oxygen Bubbles are too high up.

### ISSUE THREAD

**Issue by Ezeyra** [Fuzss/overflowingbars#1]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.0

### Notes (Required)

The bubbles that normaly appear directly above the hunger bar, now appear higher up even if the armour toughness bar is not visible.
To recreate. 
1. Launch game, enter world
2. find water
3. submerge in water
4. look at bubbles

### latest.log (Optional)

https://gist.github.com/Ezeyra/3f79334683f73c514a8a10f113ba5503

**Comment by Fuzss** [comment]
Thanks, fixed in v4.0.1.
