### ISSUE TITLE
[Suggestion]: Option to disable each individual bar modification that mo offers

### ISSUE THREAD

**Issue by GhostGH** [Fuzss/overflowingbars#32]
### Mod Loader (Optional)

Forge

### Minecraft Version(s) (Optional)

1.20.1

### Suggestion (Required)

I like everything except for health bar visual modification. I want to disable it and see my health as it would show in Vanilla if I had more hp. Reason: it's hard to keep track of your health in battle if using this mod.

**Comment by Fuzss** [comment]
Use this mod for in-game configuration: https://modrinth.com/mod/forge-config-screens

**Comment by GhostGH** [comment]
the config for this mod offers only two options:

#Render food bar when riding a mount.
food_bar = true
#Render experience bar when not jumping with a mount.
experience_bar = true

i can't solve my problem with these two. also tried adding my own config options: health_bar = false or hp_bar = false, but, ofc, they don't work

**Comment by Fuzss** [comment]
You are looking at the wrong mod, it’s Overflowing Bars.

**Comment by GhostGH** [comment]
silly me. thx for the replies!
